# Generated by Django 4.0.1 on 2022-01-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_publish_post_slug_post_timestamp_post_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='published',
        ),
    ]
