# Generated by Django 4.0.1 on 2022-01-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_timestamp_alter_post_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authour',
            new_name='author',
        ),
    ]
